{
 "title": "Workspace Detail",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "workspace_name",
    "label": "Workspace Name Filter",
    "query": {
     "query": "label_values(coderd_agents_up,workspace_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<small>**HINT**: use the dropdowns above to filter by specific workspace(s).</small>"
   }
  },
  {
   "title": "Details",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 1.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (template_name) (coderd_agents_up{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Template Name"
    },
    {
     "expr": "group by (template_version) (coderd_agents_up{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Template Version"
    },
    {
     "expr": "group by (username) (coderd_agents_up{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Owner"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1.2 },
   "options": {
    "content": "Essential information about the selected workspace."
   }
  },
  {
   "title": "Resources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 5.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*$workspace_name.*\", namespace=`coder-workspaces`, resource=\"cpu\"})",
     "legendFormat": "CPUs Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*$workspace_name.*\", namespace=`coder-workspaces`, resource=\"memory\"})",
     "legendFormat": "RAM Requested"
    },
    {
     "expr": "sum(\n  kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\".*$workspace_name.*\",namespace=`coder-workspaces`}\n  * on(persistentvolumeclaim) group_right\n  group by (persistentvolumeclaim, persistentvolume) (\n      label_replace(\n          kube_persistentvolume_claim_ref,\n          \"persistentvolumeclaim\",\n          \"$1\",\n          \"name\",\n          \"(.+)\"\n      )\n  )\n  * on (persistentvolume)\n  kube_persistentvolume_capacity_bytes\n)",
     "legendFormat": "PVC Capacity"
    }
   ]
  },
  {
   "title": "Agent Lifecycle State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (lifecycle_state) (coderd_agents_connections{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agent Startup Script Execution Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_agentstats_startup_script_seconds{workspace_name=~\"$workspace_name\"}) or vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Session Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (app) (\n    label_replace(\n        {workspace_name=~\"$workspace_name\", __name__=~\"coderd_agentstats_session_count_.*\"},\n        \"app\",\n        \"$1\",\n        \"__name__\",\n        \"coderd_agentstats_session_count_(.*)\"\n    )\n)>0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 9.2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_agents_connection_latencies_seconds{workspace_name=~\"$workspace_name\"})",
     "legendFormat": "Connection Latency"
    },
    {
     "expr": "max(sum by (pod) (sum_over_time(coderd_agentstats_rx_bytes{workspace_name=~\"$workspace_name\"}[$__range])))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "max(sum by (pod) (sum_over_time(coderd_agentstats_tx_bytes{workspace_name=~\"$workspace_name\"}[$__range])))",
     "legendFormat": "Transmitted Bytes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9.2 },
   "options": {
    "content": "Essential information about this workspace's agent.\n\nRead more about the agent [here](https://coder.com/docs/v2/latest/about/architecture#agents)."
   }
  },
  {
   "title": "Build Log",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 15.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_name, workspace_owner, status, template_name, template_version, workspace_transition) (\n  # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n  # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n  ((\n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\"} - \n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\"} offset $__interval\n  ) >= 0) \n  or coderd_workspace_builds_total{workspace_name=~\"$workspace_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15.2 },
   "options": {
    "content": "This table shows a reverse-chronological log of all workspace builds.\n\nThe \"Count\" field shows the count of events which occurred within a minute, grouped by all columns."
   }
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 22.2 },
   "targets": [
    {
     "expr": "{namespace=~`(coder|coder)`, logger=~\"(.*runner|terraform|provisioner.*)\"} |~ \"$workspace_name\" | line_format `{{ printf \"[\\033[35m\" }}{{.pod}}{{ printf \"\\033[0m]\\t\" }}{{ __line__ }}`"
    },
    {
     "expr": "{namespace=`coder-workspaces`, pod=~\".*($workspace_name).*\"} | line_format `{{ printf \"[\\033[32m\" }}{{.pod}}{{ printf \"\\033[0m]\\t\" }}{{ __line__ }}`"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 22.2 },
   "options": {
    "content": "The logs to the left come both from provisioners and workspace logs.\n\nProvisioner logs matching the name filter are highlighted in <span style=\"color:rgb(204, 0, 204)\">magenta</span>, while\nworkspace logs matching the name filter are highlighted in <span style=\"color:rgb(0, 204, 0)\">green</span>."
   }
  }
 ]
}