{
 "title": "UPS Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ups",
    "label": "UPS",
    "query": "label_values(network_ups_tools_device_info, ups)"
   }
  ]
 },
 "panels": [
  { "title": "$ups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ups" },
  {
   "title": "UPS Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{ups=\"$ups\"} == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_frequency{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Load (VA)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(network_ups_tools_output_voltage{ups=\"$ups\"} * network_ups_tools_output_current{ups=\"$ups\"}) / network_ups_tools_output_powerfactor",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Load (%)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_output_voltage{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "network_ups_tools_output_current{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "network_ups_tools_output_frequency{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Output Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_ups_tools_output_powerfactor{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Output Load (VA)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "(network_ups_tools_output_voltage{ups=\"$ups\"} * network_ups_tools_output_current{ups=\"$ups\"}) / network_ups_tools_output_powerfactor",
     "legendFormat": "{{$ups}} VA"
    }
   ]
  },
  {
   "title": "Output Load (W)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(network_ups_tools_output_voltage{ups=\"$ups\"} * network_ups_tools_output_current{ups=\"$ups\"})",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Run Time Left",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Output Load (VA)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "(network_ups_tools_output_voltage_nominal{ups=\"$ups\"} * network_ups_tools_output_current{ups=\"$ups\"}) / 0.96",
     "legendFormat": "{{$ups}} VA"
    }
   ]
  },
  {
   "title": "Output Load (W)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(network_ups_tools_output_voltage_nominal{ups=\"$ups\"} * network_ups_tools_output_current{ups=\"$ups\"})",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_temperature{ups=\"$ups\"}",
     "legendFormat": "{{$ups}}"
    }
   ]
  }
 ]
}